import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import QueryProvider from "@/libs/QueryPprovider";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body
          className={`${montserrat.className} antialiased leading-relaxed tracking-wide
                      min-h-screen grid grid-rows-[auto,1fr,auto]`}
        >
          {children}
        </body>
      </QueryProvider>
    </html>
  );
}
